#!/bin/bash
cp -rv ~/.scripts ~/.bash_profile ~/.bashrc ~/.vimrc ~/.xinitrc ~/.Xresources ~/Projects/dotfiles/
cp -rv ~/.config/ranger ~/.config/i3  ~/.config/i3status ~/.config/wall.jpeg ~/Projects/dotfiles/.config/
